In [1]:
import numpy as np

In [2]:
v = np.linspace(0,10,5)

In [3]:
v[0]

0.0

In [4]:
v[1]

2.5

In [5]:
v[-1]

10.0

In [6]:
v[5]

IndexError: index out of bounds

In [7]:
vv = np.random.random((5,4))

In [8]:
vv

array([[ 0.96967018,  0.49954885,  0.89959193,  0.81930628],
       [ 0.10359908,  0.70108773,  0.8202162 ,  0.29045088],
       [ 0.93170025,  0.02691297,  0.49401199,  0.98829252],
       [ 0.59182274,  0.18804766,  0.72693668,  0.03495318],
       [ 0.78738115,  0.783917  ,  0.9351    ,  0.50475656]])

In [9]:
vv[0,0]

0.96967017916969267

In [10]:
vv[4,3]

0.50475655794147178

In [11]:
ll = [[1,2,3],[4,5,6],[7,8,9]]

In [12]:
ll

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
ll[1,2]

TypeError: list indices must be integers, not tuple

In [14]:
ll[1][2]

6

In [15]:
v[2:4]

array([ 5. ,  7.5])

In [16]:
vv[2:5,1]

array([ 0.02691297,  0.18804766,  0.783917  ])

In [17]:
vv[2:5,1:2]

array([[ 0.02691297],
       [ 0.18804766],
       [ 0.783917  ]])

In [18]:
vv[2:-1,:]

array([[ 0.93170025,  0.02691297,  0.49401199,  0.98829252],
       [ 0.59182274,  0.18804766,  0.72693668,  0.03495318]])

In [19]:
vv[:,::2]

array([[ 0.96967018,  0.89959193],
       [ 0.10359908,  0.8202162 ],
       [ 0.93170025,  0.49401199],
       [ 0.59182274,  0.72693668],
       [ 0.78738115,  0.9351    ]])

In [20]:
v2 = v[2:4]

In [21]:
v2

array([ 5. ,  7.5])

In [22]:
v2[0] = 0

In [23]:
v2

array([ 0. ,  7.5])

In [24]:
v

array([  0. ,   2.5,   0. ,   7.5,  10. ])

In [25]:
v3=v[2:4].copy()

In [27]:
v3[0]=1
v3

array([ 1. ,  7.5])

In [29]:
v

array([  0. ,   2.5,   0. ,   7.5,  10. ])

In [30]:
v[[1,2,3]]

array([ 2.5,  0. ,  7.5])

In [31]:
bool_index = v > 0

In [32]:
bool_index

array([False,  True, False,  True,  True], dtype=bool)

In [33]:
v[bool_index]

array([  2.5,   7.5,  10. ])

In [34]:
v

array([  0. ,   2.5,   0. ,   7.5,  10. ])

In [35]:
vv[vv > 0.5] = vv[vv > 0.5] * 2

In [36]:
vv

array([[ 1.93934036,  0.49954885,  1.79918386,  1.63861256],
       [ 0.10359908,  1.40217545,  1.64043239,  0.29045088],
       [ 1.86340051,  0.02691297,  0.49401199,  1.97658504],
       [ 1.18364547,  0.18804766,  1.45387335,  0.03495318],
       [ 1.5747623 ,  1.56783399,  1.8702    ,  1.00951312]])