#Numpy - create multi-dimentional array
- long set of number
- need math operation
## what different from python default containers
- organize data faster and memory efficient
- NumPy dtypes > Integers: numpy.int8, numpy.int16, numpy.int32*, numpy.int64, Unsigned: numpy.uint8 etc.
- NumPy dtypes > Floating-point numbers: numpy.float32, numpy.float64*, numpy.float128, Complex: numpy.complex64  
- Need to specify data 
## Learning objectives
1. creating arrays: from a list, empty, zero, random, and linearly spaced
2. Interrogating the dtype and shape of arrays
3. Composing arrays
4. Loading and saving arrays

In [1]:
import numpy as np
import matplotlib.pyplot as pp

In [2]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
a.dtype

dtype('int64')

In [4]:
a = np.array([1,2,3,4,5],dtype=np.float64)
a

array([ 1.,  2.,  3.,  4.,  5.])

In [5]:
a.dtype

dtype('float64')

In [6]:
a.ndim, a.shape, a.size

(1, (5,), 5)

In [8]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]],dtype=np.float64)
b

array([[  1.,   2.,   3.,   4.,   5.],
       [  6.,   7.,   8.,   9.,  10.]])

In [9]:
b.ndim, b.shape, b.size

(2, (2, 5), 10)

In [10]:
np.zeros((3,3),'d')

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [11]:
np.empty((4,4),'d')

array([[  6.93106345e-310,   6.93106345e-310,   1.58101007e-322,
          1.27319747e-313],
       [  1.27319747e-313,   1.27319747e-313,   6.93086265e-310,
          2.10517605e-313],
       [  6.93105803e-310,   6.93086265e-310,   3.35423452e-313,
          6.93086265e-310],
       [  4.20303284e-313,   1.63041663e-322,   2.38391891e-316,
          6.93106345e-310]])

In [12]:
np.linspace(0,10,5)

array([  0. ,   2.5,   5. ,   7.5,  10. ])

In [13]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [14]:
np.random.standard_normal((2,4))

array([[ 0.62495239,  0.17183298,  0.60630794,  0.207561  ],
       [-0.09034912, -0.95887614,  0.44244243, -1.50299516]])

In [15]:
a = np.random.standard_normal((2,3))
b = np.random.standard_normal((2,3))

np.vstack([a,b])

array([[ 1.16151607, -0.09678153, -1.32455145],
       [-0.52574654,  2.16203335, -0.49754583],
       [ 0.81537238, -0.13450604, -1.19178245],
       [ 1.19050902,  2.95953944, -2.08138612]])

In [16]:
np.hstack([a,b])

array([[ 1.16151607, -0.09678153, -1.32455145,  0.81537238, -0.13450604,
        -1.19178245],
       [-0.52574654,  2.16203335, -0.49754583,  1.19050902,  2.95953944,
        -2.08138612]])

In [17]:
a.transpose()

array([[ 1.16151607, -0.52574654],
       [-0.09678153,  2.16203335],
       [-1.32455145, -0.49754583]])

In [18]:
np.save('example.npy',a)

In [19]:
a1 = np.load('example.npy')

In [20]:
a1

array([[ 1.16151607, -0.09678153, -1.32455145],
       [-0.52574654,  2.16203335, -0.49754583]])